### PR TITLE
[BD-6] Move to tox

### PR DESCRIPTION
**Pull request by morenol**
This PR moves the tests to pytest + tox, it is not upgrading any package, it only removes of nose related packages and add pytest to the test requirements.

The idea behind this is to create smaller PRs, since the last attempts to add oep18 to this repository have failed.

## Reviewers
- [x] @awais786 
- [x] ericfab179

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @morenol! I've created [BLENDED-426](https://openedx.atlassian.net/browse/BLENDED-426) to keep track of it in Jira.  More details are on the [BD-06](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1594000004/BD-06+Python+3.8+Upgrade) project page.

When this pull request is ready, tag your edX technical lead.

**Comment by awais786** [comment]
@sethmccann Please review this PR.

**Review by jhan217 — COMMENTED** [review]
This PR looks alright. Couple of things I noticed:
1. github branch issue - "This branch is out-of-date with the base branch" issue. Could you update this branch so that it's up to date?
2. I was able to successfully run `make tests` and `make quality` in a local virtualenv (python 2.7.16). However, I did notice a couple warnings from the `make quality` command and wasn't sure if they impacted anything:
```ERROR: pytest-cov 2.10.0 has requirement coverage>=4.4, but you'll have coverage 4.0.3 which is incompatible.```
```ERROR: pylint-plugin-utils 0.6 has requirement pylint>=1.7, but you'll have pylint 1.6.4 which is incompatible.```

**Comment by morenol** [comment]
@jhan217 PR rebased.

Thank you for noticing that. I was able to replicate them.

I added explicit contraints to 

pylint==1.6.4
pylint-django==0.7.2
pylint-plugin-utils==0.2.1

and upgraded the contraint of

coverage==4.4.0
six==1.15.0 (had warning conflicts with the tox version installed)

In another PR I can try again to make this oep18 compliant.

**Review by jhan217 — APPROVED** [review]
Looks good. I was able to run `make requirements`, `make quality`, and `make test` without any issues locally, aside from deprecation warnings.

**Comment by jhan217** [comment]
It looks like there's a couple other reviewers mentioned in the PR description - @awais786 and/or @ericfab179, do you have any thoughts on this PR? Also, it looks like this ticket has a `rejected` tag - does this mean this PR should not be merged?

**Comment by morenol** [comment]
Regarding the issue in Jira, I think that it was rejected by mistake. That was rejected by the Open Source Pull Request Bot, I think that it was done when I closed and opened again this PR 20 days ago.

**Review by awais786 — APPROVED** [review]

**Review by ericfab179 — APPROVED** [review]

**Pull request merged**
