### PR TITLE
[BD-6] Switch to python3

### PR DESCRIPTION
**Pull request by morenol**
This PR make this:

  - Add tests in python3
  - Change httprety with responses
  - Use a different version of edx-rest-api-client for python3.5

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @morenol! I've created [BLENDED-351](https://openedx.atlassian.net/browse/BLENDED-351) to keep track of it in Jira.   More details are on the [BD-06](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1594000004/BD-06+Python+3.8+Upgrade) project page.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by awais786** [comment]
@morenol Please squash.

**Comment by morenol** [comment]
> @morenol Please squash.

Please review this PR first https://github.com/edx/ecommerce-worker/pull/61, I will rebase and squash this in top of that

**Comment by jmbowman** [comment]
An updated ecomworker Docker image is now available: https://hub.docker.com/r/edxops/ecomworker/tags .  Is anything else blocking this?

**Comment by morenol** [comment]
@jmbowman I decided to split these changes in several PRs, the first part is in here https://github.com/edx/ecommerce-worker/pull/63

It only needs a review from someone of the team owner of this repo. Once that is merged I can try the next changes.

In the past we merged this, https://github.com/edx/ecommerce-worker/pull/61 but then we had to revert that due to a problem in the e2e-tests,  for that reason I made a new PR with less changes and with less upgrades in the python dependencies to see if we can start with that.

**Comment by morenol** [comment]
Addressed in #96

**Pull request closed without merging**
