### PR TITLE
[BD-6] Change httpretty with responses

### PR DESCRIPTION
**Pull request by morenol**
Change httpretty with [responses](https://github.com/getsentry/responses) because the current version of httpretty is from 2015, does not have support for python 3.5 and if we upgrade that version the test suite gets broken due to https://github.com/gabrielfalcao/HTTPretty/pull/202

This will be needed for the migration to python3.

## Reviewers
- [x] @awais786

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @morenol! I've created [BLENDED-533](https://openedx.atlassian.net/browse/BLENDED-533) to keep track of it in Jira.   More details are on the [BD-06](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1594000004/BD-06+Python+3.8+Upgrade) project page.


When this pull request is ready, tag your edX technical lead.

**Review by awais786 — APPROVED** [review]

**Comment by awais786** [comment]
@jhan217 please review.

**Comment by awais786** [comment]
@jhan217 please review.

**Comment by jhan217** [comment]
The review work is prioritized/tracked on our side with https://openedx.atlassian.net/browse/REV-1277. That being said, pinging @emma-green on on this as well

**Review by mzulqarnain1 — APPROVED** [review]

**Review by mraarif — APPROVED** [review]

**Review by awais786 — APPROVED** [review]

**Pull request merged**
