### PR TITLE
build: add python 3.11 and 3.12 ci checks

### LINKED ISSUE #262: [ecommerce-worker] Test Python 3.11 and 3.12

### PR DESCRIPTION
**Pull request by Danyal-Faheem**
**Changes**

- Added CI checks as part of the [upgrade process](https://github.com/openedx/ecommerce-worker/issues/262) to python 3.11 and python 3.12.
- Also fixes one part of the [downstream issue](https://github.com/overhangio/tutor-ecommerce/issues/78) in tutor-ecommerce.
- Updated `docker-compose` to `docker compose`.
- Added a check on code coverage to only run for python 3.8 as we don't need to unnecessarily run it for every python verrsion.

# ⛔️ MAIN BRANCH WARNING! 2U EMPLOYEES must make branches against the 2u/main BRANCH

- [x] I have checked the branch to which I would like to merge.

# ⛔️ DEPRECATION WARNING

**This repository is deprecated and in maintainence-only operation while we work on a replacement, please see [this announcement](https://discuss.openedx.org/t/deprecation-removal-ecommerce-service-depr-22/6839) for more information.**

Although we have stopped integrating new contributions, we always appreciate security disclosures and patches sent to [security@edx.org](mailto:security@edx.org)

## If you're merging to master (not 2u/main) branch...

**Merge checklist:**
- [x] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `base.in` if needed in production
    - `test.in` for test requirements
    - `make upgrade && make requirements` have been run to regenerate requirements
- [x] [Version](https://github.com/openedx/ecommerce-worker/blob/master/setup.py) bumped

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/openedx/ecommerce-worker/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [GitHub CI](https://github.com/openedx/ecommerce-worker/actions?query=workflow%3A%22Python+CI%22), verify version has been pushed to [PyPI](https://pypi.org/project/edx-ecommerce-worker/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [ecommerce](https://github.com/openedx/ecommerce) to upgrade dependencies (including ecommerce-worker)
    - This **must** be done after the version is visible in PyPi as `make upgrade` in ecommerce will look for the latest version in PyPi.
    - Note: the ecommerce-worker constraint in ecommerce **must** also be bumped to the latest version in PyPi.
- [ ] Deploy `ecommerce`
- [ ] Deploy `ecomworker`

### CODE REVIEW

**Comment by DawoudSheraz** [comment]
@feanil Hi. Can you run the workflows on this PR, please? Thanks

**Review by johanseto — COMMENTED** [review]
Hi I run in a fork this PR and I have 2 comments:

- The lint commit would fail because `ci` is not in the allowed words for commitlint. You can change it to `test`.
image

- I want to understand if the tests would run in python 3.11 and 3.12.
 Because In those tests the test_target shows 3.8


Also, I suspect in quality target tests are using the python3.8.


I think the problem is that the quality env is in python3.12, but the tests are running in the _edxops/ecomworker_ docker image and there is 3.8.

Also this line https://github.com/openedx/ecommerce-worker/blob/f852676a216b35ee845af66eb142ff657d72f98f/.github/workflows/ci.yml#L33
The python3-dev package seems installing with python3.8
image

**Comment by feanil** [comment]
@Danyal-Faheem looks like you need to fix the commit messages so the conform to [OEP-51](https://docs.openedx.org/projects/openedx-proposals/en/latest/best-practices/oep-0051-bp-conventional-commits.html#specification) and rebase this on top of master and then it should be good to merge.  Let me know when that's done and I can help land it.

**Comment by DawoudSheraz** [comment]
> @Danyal-Faheem looks like you need to fix the commit messages so the conform to [OEP-51](https://docs.openedx.org/projects/openedx-proposals/en/latest/best-practices/oep-0051-bp-conventional-commits.html#specification) and rebase this on top of master and then it should be good to merge. Let me know when that's done and I can help land it.

Hey Feanil. It needs some changes in Dockerfile (just like Discovery and e-commerce repositories). It's on our radar, we will try to get it done as soon as possible. Once merged, we will backport this to redwood.master.

**Comment by Danyal-Faheem** [comment]
Hi @feanil, I've made the required changes, can you trigger the workflows here and also review this PR for me? Thank you.

**Review by johanseto — APPROVED** [review]
After the last commit, tests are also running in python 3.11 and 3.12 =)

**Comment by Danyal-Faheem** [comment]
Hi @feanil, this PR is ready to be merged. Can you take a look and merge this for me? Thanks.

**Review by DawoudSheraz — APPROVED** [review]

**Review by feanil — APPROVED** [review]

**Comment by feanil** [comment]
@Danyal-Faheem please tag me on the backport PR as well though I think the BTR release manager can merge that as well I just want to know when it lands.

**Pull request merged**
